baseURL: "https://qinyu.github.io"
languageCode: zh-cn
title: Qin Yu is writing
theme: anatole
taxonomies:
  category: categories
  series: series
  tag: tags
mainSections:
  - post
defaultContentLanguage: zh-cn
