title: 覃宇码字的地方
author: 覃宇
contentratio: 0.7
favicon: "favicons/"
description: |
  Thoughtworker
  移动应用架构师
  技术教练
profilePicture: images/profile.jpg
googleAnalytics: false
socialIcons:
  - icon: fab fa-github
    title: GitHub
    url: https://github.com/qinyu/
  - icon: fas fa-envelope
    title: e-mail
    url: 'mailto:qinyusuain@gmail.com'
